debtcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('debtors/', views.DebtorList.as_view(), name='debtors_list'),
    path('debtors/<int:debtor_id>/', views.debtors_detail, name='detail'),
    path('debtors/create/', views.DebtorCreate.as_view(), name='debtors_create'),
    path('debtors/<int:pk>/update', views.DebtorUpdate.as_view(), name='debtors_update'),
    path('debtors/<int:pk>/delete', views.DebtorDelete.as_view(), name='debtors_delete'),
    path('debtors/<int:debtor_id>/add_payment/', views.add_payment, name='add_payment'),
    path('debtors/<int:debtor_id>/assoc_insurance/<int:insurance_id>/', views.assoc_insurance, name='assoc_insurance'),
    path('insurance/', views.InsuranceList.as_view(), name='insurance_index'),
    path('insurance/create/', views.InsuranceCreate.as_view(), name='insurance_create'),
    path('insurance/<int:pk>/delete/', views.InsuranceDelete.as_view(), name='insurance_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator

# Create your models here.
class Insurance(models.Model):
  description = models.CharField(max_length=50)

  def __str__(self):
    return self.description

  def get_absolute_url(self):
    return reverse('insurance_index')

class Debtor(models.Model):
    name = models.CharField(max_length=100)
    debt = models.IntegerField()
    age = models.IntegerField()
    insurance = models.ManyToManyField(Insurance, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'debtor_id': self.id})

    def paid_off(self):
        return self.debt == 0

class Payment(models.Model):
    date = models.DateField()
    payment = models.IntegerField(
        default=1,
        validators=[
            MinValueValidator(1)
        ]
    )
    debtor = models.ForeignKey(Debtor, on_delete=models.CASCADE)

    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.payment} on {self.date}"
    
    class Meta:
        ordering = ['date']
  

main_app/forms.py
from django.forms import ModelForm
from .models import Payment

class PaymentForm(ModelForm):
  class Meta:
    model = Payment
    fields = ['date', 'payment']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Debtor, Insurance
from .forms import PaymentForm


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def debtors_detail(request, debtor_id):
  debtor = Debtor.objects.get(id=debtor_id)
  insurance_debtor_doesnt_have = Insurance.objects.exclude(id__in = debtor.insurance.all().values_list('id'))
  payment_form = PaymentForm()
  return render(request, 'debtors/detail.html', {
    'debtor': debtor, 'payment_form': payment_form,
    'insurance': insurance_debtor_doesnt_have
  })

def add_payment(request, debtor_id):
  form = PaymentForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_payment = form.save(commit=False)
    new_payment.debtor_id = debtor_id
    new_payment.save()
    debtor = Debtor.objects.get(id=debtor_id)
    debtor.debt = debtor.debt - new_payment.payment
    debtor.save()
  return redirect('detail', debtor_id=debtor_id)

def assoc_insurance(request, debtor_id, insurance_id):
  Debtor.objects.get(id=debtor_id).insurance.add(insurance_id)
  return redirect('detail', debtor_id=debtor_id)

class DebtorList(ListView):
  model = Debtor

class DebtorDetail(DetailView):
  model = Debtor

class DebtorCreate(CreateView):
  model = Debtor
  fields = ['name', 'debt', 'age']

class DebtorUpdate(UpdateView):
  model = Debtor
  fields = ['debt', 'age']

class DebtorDelete(DeleteView):
  model = Debtor
  success_url = '/debtors/'

class InsuranceList(ListView):
  model = Insurance

class InsuranceCreate(CreateView):
  model = Insurance
  fields = '__all__'

class InsuranceDelete(DeleteView):
  model = Insurance
  success_url = '/Insurances/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Debt Collector</h1>
<hr />
<p>Hire the Debt Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Debt Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/mycssstyle.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;DebtCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'insurance_create' %}">Add new insurance</a></li>
          <li><a href="{% url 'insurance_index' %}">View All insurance</a></li>
          <li><a href="{% url 'debtors_create' %}">Add a Debtor</a></li>
          <li><a href="{% url 'debtors_list' %}">Debtors</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="nav page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Debt Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/debtors/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Debtor Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ debtor.name }}</span>
        <p>Debt Value: <b>$</b>{{ debtor.debt }}</p>
        <p>Age: {{ debtor.age }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'debtors_update' debtor.id %}">Edit</a>
        <a href="{% url 'debtors_delete' debtor.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_payment' debtor.id %}" method="post">
      {% csrf_token %}
      {{ payment_form.as_p }}
      <input type="submit" class="btn" value="Add Payment">
    </form>
    <br>
    {% if debtor.paid_off %}
      <div class="card-panel teal-text center-align">The debt has been paid off!</div>
    {% else %}
      <div class="card-panel red-text center-align">You have outstanding balance!</div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Payment</th></tr>
      </thead>
      <tbody>
        {% for payment in debtor.payment_set.all %}
          <tr>
            <td>{{payment.date}}</td>
            <td><b>$</b>{{payment.payment}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ debtor.name }}'s Insurance</h3>
    {% if debtor.insurance.count %}
      {% for insurance in debtor.insurance.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span> {{ insurance.description }}</span>
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Insurance :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Insurance</h3>
    {% if insurance.count %}
      {% for ins in insurance.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ ins.description }}</span>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_insurance' debtor.id ins.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cat.name}} Already Has All Insurance Available</h5>
    {% endif %}
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/debtors/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Debtor List</h1>

{% for debtor in debtors %}
  <div class="card">
    <a href="{% url 'detail' debtor.id %}">
      <div class="card-content">
        <span class="card-title"><b>{{ debtor.name }}</b></span>
        <p>Debts Value: <b>$</b>{{ debtor.debts }}</p>
        <p>Age: {{ debtor.age }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>You Owe Money</h1>

{% endblock %}

main_app/templates/main_app/debtor_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'debtors_detail' debtor.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/debtor_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Debtor</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/debtor_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Debtor List</h1>

{% for debtor in object_list %}
  <div class="card">
    <a href="{% url 'detail' debtor.id %}">
      <div class="card-content">
        <span class="card-title"><b>{{ debtor.name }}</b></span>
        <p>Debts Value: <b>$</b>{{ debtor.debt }}</p>
        <p>Age: {{ debtor.age }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/insurance_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Insurance</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/insurance_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Insurance List</h1>

{% for insurance in object_list %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ insurance.description }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}